/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import javax.swing.JOptionPane;
import objects.Moneda;

/**
 *
 * @author gomin
 */
public class InterfazConversorMonedas extends javax.swing.JFrame {

    /**
     * Creates new form Interfz_principal
     */
    
    String[] options = {"Pesos a Dólares","Pesos a Euros","Pesos a Libras Esterlinas","Pesos a Yen Japonés","Pesos a Won sur-coreano","Dólares a Pesos",
        "Euros a Pesos","Libras Esterlinas a Pesos","Yen Japonés a Pesos","Won sur-coreanos a Pesos"};
    public InterfazConversorMonedas() {
        initComponents();
        //Se limpia el combo y se le mandan los items
        cb_options.removeAllItems();
        int len = options.length;
        for (int i = 0; i <len; i++){
            cb_options.addItem(options[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_conversor = new javax.swing.JPanel();
        cb_options = new javax.swing.JComboBox<>();
        tf_value = new javax.swing.JTextField();
        btn_convertir_moneda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p_conversor.setBorder(javax.swing.BorderFactory.createTitledBorder("Conversor"));

        cb_options.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_optionsActionPerformed(evt);
            }
        });

        btn_convertir_moneda.setText("Convertir");
        btn_convertir_moneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_convertir_monedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_conversorLayout = new javax.swing.GroupLayout(p_conversor);
        p_conversor.setLayout(p_conversorLayout);
        p_conversorLayout.setHorizontalGroup(
            p_conversorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_conversorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb_options, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_value, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_convertir_moneda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_conversorLayout.setVerticalGroup(
            p_conversorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_conversorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_conversorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_convertir_moneda))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_conversor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_conversor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_optionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_optionsActionPerformed
        
        
    }//GEN-LAST:event_cb_optionsActionPerformed

    private void btn_convertir_monedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_convertir_monedaActionPerformed
        objects.Moneda moneda = new objects.Moneda();
        int option = cb_options.getSelectedIndex();
        Double value = 0.00;
        String result;
        moneda.setOption(option);
        try{
            value = Double.valueOf(tf_value.getText());
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Ingresa un valor valido, como:\n 123.50\n"+e.toString());
        }
        if (value > 0.00){
            moneda.setValue(value);
            result = moneda.cadena();
            JOptionPane.showConfirmDialog(rootPane, result);
        }
        
        
    }//GEN-LAST:event_btn_convertir_monedaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazConversorMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazConversorMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazConversorMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazConversorMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazConversorMonedas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_convertir_moneda;
    private javax.swing.JComboBox<String> cb_options;
    private javax.swing.JPanel p_conversor;
    private javax.swing.JTextField tf_value;
    // End of variables declaration//GEN-END:variables
}
